# fly.toml app configuration file generated for telegram-audiodiary-bot-late-paper-9930 on 2025-11-16T16:19:08+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'telegram-audiodiary-bot-late-paper-9930'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
